GLOBAL.TUNING.WERE_SANITY_PENALTY = -.15
GLOBAL.TUNING.SKILLS.WOODIE.MOOSE_HEALTH_REGEN = { -- (0.3 / seg)
    amount = 1,
    period = 4
}
GLOBAL.TUNING.SKILLS.WOODIE.WERESKILL_WERENESS_CONSUMPTION = {
    BEAVER = -5,
    GOOSE = -10
}